version: '3.8'

services:
  api_gateway:
    image: api_gateway_image
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    depends_on:
      - gestion_pedidos

  gestion_pedidos:
    image: gestion_pedidos_image
    build:
      context: ./gestion_pedidos
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestion_pedidos_db
    ports:
      - "5432:5432"
