version: '3.8'

services:
  api_gateway:
    image: api_gateway_image
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    depends_on:
      - gestion_pedidos
      - gestion_inventarios
      - gestion_compras

  gestion_pedidos:
    image: gestion_pedidos_image
    build:
      context: ./gestion_pedidos
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=sqlite:///pedidos.db
      - DATABASE_PORT=5432

  gestion_inventarios:
    image: gestion_inventarios_image
    build:
      context: ./gestion_inventarios
      dockerfile: Dockerfile
    ports:
      - "3033:3033"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5454

  gestion_compras:
    image: gestion_compras_image
    build:
      context: ./gestion_compras
      dockerfile: Dockerfile
    ports:
      - "4043:4043"
    environment:
      - DATABASE_HOST=sqlite:///compras.db
      - DATABASE_PORT=5423
